spring:
  application:
    name: springboot-FirebaseAuth
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com"
    issuer-uri: "https://securetoken.google.com/springboot-firebaseauth"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+1
  h2:
    console.enabled: true
    console.path: /h2-console
    jdbc-url: jdbc:h2:~/firebase;DB_CLOSE_ON_EXIT=FALSE
    username: firebase
    password: firebase
    driverClassName: org.h2.Drive


logging:
  level:
    org.springframework.web: DEBUG